version: "3.8"
services:
  # Flowise IA (novo!)
  flowise:
    image: flowiseai/flowise
    container_name: gamibook-flowise
    ports:
      - "3000:3000"
    environment:
      OLLAMA_BASE_URL: "http://host.docker.internal:11434"
    volumes:
      - ./docker/flowise_data:/root/.flowise
    restart: unless-stopped
    # Directus já roda separado
